import React, { useState } from 'react';
import { motion } from 'motion/react';
import { SmartPageSchema, getColumnWidth } from './builderTypes';
import { X, Code, Copy, Check, Download } from 'lucide-react';

interface ExportModalProps {
  pageSchema: SmartPageSchema;
  onClose: () => void;
}

export const ExportModal: React.FC<ExportModalProps> = ({ pageSchema, onClose }) => {
  const [exportFormat, setExportFormat] = useState<'react' | 'html' | 'json'>('react');
  const [copied, setCopied] = useState(false);

  const generateReactCode = () => {
    return `import React from 'react';

// Generated by Smart Page Builder (Intelligent Layout Engine)
// Page: ${pageSchema.title}

export default function SmartPage() {
  return (
    <div className="smart-page-wrapper w-full font-sans rtl text-right bg-white dark:bg-slate-900">
      {/* Sections rendering */}
      ${pageSchema.sections
        .map(
          (sec, i) => `
      <section className="page-section section-${i + 1} py-10">
        <div className="${sec.layout === 'boxed' ? 'max-w-[1200px] mx-auto px-4' : 'w-full px-4'}">
          <div className="grid grid-cols-12 gap-6">
            ${sec.columns
              .map(
                (col) => `
            <div className="col-span-${getColumnWidth(col, 'mobile')} md:col-span-${getColumnWidth(col, 'tablet')} lg:col-span-${getColumnWidth(col, 'desktop')}">
              ${col.widgets
                .map(
                  (w) => `
              {/* Widget: ${w.title} (${w.type}) */}
              <div className="widget-block my-3">
                ${w.type === 'heading' ? `<h2 className="text-2xl font-black">${w.content}</h2>` : ''}
                ${w.type === 'text' ? `<p className="text-sm leading-relaxed">${w.content}</p>` : ''}
                ${w.type === 'button' ? `<a href="${w.buttonUrl || '#'}" className="inline-block px-6 py-3 rounded-xl bg-teal-600 text-white font-bold">${w.buttonText || 'دکمه اقدام'}</a>` : ''}
                ${w.type.includes('feed') || w.type.includes('staff') || w.type.includes('file') ? `<div className="dynamic-module-bound border rounded-2xl p-4">[Smart Binding: ${w.type}]</div>` : ''}
              </div>`
                )
                .join('\n')}
            </div>`
              )
              .join('\n')}
          </div>
        </div>
      </section>`
        )
        .join('\n')}
    </div>
  );
}`;
  };

  const generateHtmlCode = () => {
    return `<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
  <meta charset="UTF-8">
  <title>${pageSchema.title}</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <link href="https://cdn.jsdelivr.net/gh/rastikerdar/vazirmatn@v33.003/Vazirmatn-font-face.css" rel="stylesheet" type="text/css" />
  <style>
    body { font-family: 'Vazirmatn', sans-serif; }
  </style>
</head>
<body class="bg-slate-50 text-slate-900">
  <main className="w-full">
    ${pageSchema.sections
      .map(
        (sec) => `
    <section style="background-color: ${sec.backgroundColor || '#ffffff'}; padding-top: ${sec.paddingTop}px; padding-bottom: ${sec.paddingBottom}px;">
      <div class="${sec.layout === 'boxed' ? 'max-w-[1200px] mx-auto px-4' : 'w-full px-4'}">
        <div class="grid grid-cols-12 gap-6">
          ${sec.columns
            .map(
              (col) => `
          <div class="col-span-${getColumnWidth(col, 'mobile')} md:col-span-${getColumnWidth(col, 'tablet')} lg:col-span-${getColumnWidth(col, 'desktop')}">
            ${col.widgets
              .map(
                (w) => `
            <div class="mb-4">
              <p class="text-xs text-slate-600">${w.content}</p>
            </div>`
              )
              .join('\n')}
          </div>`
            )
            .join('\n')}
        </div>
      </div>
    </section>`
      )
      .join('\n')}
  </main>
</body>
</html>`;
  };

  const currentCode =
    exportFormat === 'react'
      ? generateReactCode()
      : exportFormat === 'html'
      ? generateHtmlCode()
      : JSON.stringify(pageSchema, null, 2);

  const handleCopy = () => {
    navigator.clipboard.writeText(currentCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 dark:bg-black/80 backdrop-blur-md rtl text-right transition-colors">
      <motion.div
        initial={{ opacity: 0, scale: 0.95 }}
        animate={{ opacity: 1, scale: 1 }}
        className="bg-white dark:bg-slate-900 border border-gray-200 dark:border-slate-700/80 rounded-3xl w-full max-w-3xl max-h-[85vh] flex flex-col overflow-hidden shadow-2xl text-slate-900 dark:text-white"
      >
        <div className="flex items-center justify-between p-6 border-b border-gray-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-950/60">
          <div className="flex items-center gap-3">
            <div className="p-2.5 rounded-2xl bg-teal-50 dark:bg-teal-500/20 text-teal-600 dark:text-teal-400 border border-teal-200 dark:border-teal-500/30">
              <Code className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-lg font-black text-slate-900 dark:text-white">دریافت کد خروجی صفحه (Code Export Engine)</h2>
              <p className="text-xs text-slate-500 dark:text-slate-400">تولید خودکار کامپوننت React، کد HTML و Schema درایور</p>
            </div>
          </div>
          <button onClick={onClose} className="p-2 rounded-xl text-slate-400 hover:text-slate-700 dark:hover:text-white hover:bg-slate-100 dark:hover:bg-slate-800">
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="flex items-center justify-between p-4 border-b border-gray-200 dark:border-slate-800 bg-slate-50/80 dark:bg-slate-900 text-xs">
          <div className="flex items-center gap-2">
            <button
              onClick={() => setExportFormat('react')}
              className={`px-4 py-2 rounded-xl font-bold transition-all cursor-pointer ${
                exportFormat === 'react' ? 'bg-teal-600 dark:bg-teal-500 text-white dark:text-slate-950 shadow-md' : 'text-slate-500'
              }`}
            >
              کامپوننت JSX / React
            </button>
            <button
              onClick={() => setExportFormat('html')}
              className={`px-4 py-2 rounded-xl font-bold transition-all cursor-pointer ${
                exportFormat === 'html' ? 'bg-teal-600 dark:bg-teal-500 text-white dark:text-slate-950 shadow-md' : 'text-slate-500'
              }`}
            >
              کد HTML + Tailwind
            </button>
            <button
              onClick={() => setExportFormat('json')}
              className={`px-4 py-2 rounded-xl font-bold transition-all cursor-pointer ${
                exportFormat === 'json' ? 'bg-teal-600 dark:bg-teal-500 text-white dark:text-slate-950 shadow-md' : 'text-slate-500'
              }`}
            >
              ساختار JSON Schema
            </button>
          </div>

          <button
            onClick={handleCopy}
            className="px-4 py-2 rounded-xl bg-teal-600 dark:bg-teal-500 hover:bg-teal-700 text-white dark:text-slate-950 font-black text-xs flex items-center gap-2 cursor-pointer shadow-md"
          >
            {copied ? <Check className="w-4 h-4 text-emerald-300 dark:text-emerald-950" /> : <Copy className="w-4 h-4" />}
            <span>{copied ? 'کپی شد!' : 'کپی تمام کد'}</span>
          </button>
        </div>

        <div className="p-6 overflow-y-auto flex-1">
          <textarea
            readOnly
            rows={14}
            value={currentCode}
            className="w-full p-4 rounded-2xl bg-slate-50 dark:bg-slate-950 border border-gray-200 dark:border-slate-800 text-xs text-teal-700 dark:text-teal-300 focus:outline-none"
          />
        </div>
      </motion.div>
    </div>
  );
};
